name: Build (Windows)

on:
  pull_request:

jobs:
  build_windows:
    uses: ./.github/workflows/_build.yml
    with:
      os: windows-latest
      platform: windows
      version_label: pr-${{ github.event.pull_request.number }}
