name: Build (macOS)

on:
  pull_request:

jobs:
  build_macos:
    uses: ./.github/workflows/_build.yml
    with:
      os: macos-latest
      platform: macos
      version_label: pr-${{ github.event.pull_request.number }}
